# Generated by Django 4.0.4 on 2025-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active status'),
        ),
    ]
