# Generated by Django 4.0.4 on 2025-02-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('P', 'paypal'), ('S', 'stripe')], max_length=1),
        ),
    ]
